### ISSUE TITLE
PXE template does not work?

### ISSUE THREAD

**Issue by helge000** [kireevco/wimaging#25]
I am trying to figure out how the PXE template is working. So far, only hard coding the boot files works for me. Maybe you can help me with some insight.

Shouldn't the template download the files required from installation media? If so, can this work by using the ps - scripts; the boot wim is not pushed to right folder?

```
Warning!

There was an error rendering the WAIK default PXELinux template: undefined method 'arch' for Host::Managed::Jail (Host::Managed)
```

Replacing `arch` with some other host marco `@host.architecture` I got form [here](http://projects.theforeman.org/projects/foreman/wiki/TemplateWriting) does no good either:

```
PXELinux template: undefined method 'bootfile' for Operatingsystem
```

Btw, I am running foreman 1.9.1

**Comment by DimmKirr** [comment]
Hi, sorry to hear you are having trouble, Daniel,
1. Which foreman version are you running/have you applied patches for this functionality?
2. Do you have safe mode enabled in foreman? Try disabling.

Please report back with results when you have a chance.
