### ISSUE TITLE
pxelinux template issue

### ISSUE THREAD

**Issue by ishtartec** [kireevco/wimaging#28]
Hi,
the issue is not with the template itself but with the PXE netboot:
Currently using foreman 1.9 and Ubuntu 14
1. linux.c32 is not included by default in tftp, so I've copied the one from: /usr/lib/syslinux/linux.c32
2. Using linux.c32 from syslinux 5 does not seem an option as booting complains about "not a COM32R" image, so I just keep the original from ubuntu.
3. When using the "original template":

```
DEFAULT menu
LABEL menu
     COM32 linux.c32 boot/wimboot
     APPEND initrdfile=boot/windows-x64/bcd,boot/windows-x64/boot.sdi,boot/windows-x64/boot.wim
```

The netboot ends with Kernel load failure (insufficient memory?)
1. Trying a adding boot/wimboot to append:

```
DEFAULT menu
LABEL menu
     COM32 linux.c32
     APPEND boot/wimboot initrdfile=boot/windows-x64/bcd,boot/windows-x64/boot.sdi,boot/windows-x64/boot.wim
```

This goes a bit better but errors in:

```
wimboot v2.5.1 -- Windows Imaging Format bootloader -- http://ipxe.org/wimboot

Command line: "BOOT_IMAGE=boot/wimboot initrdfile=boot/windows-x64/bcd,boot/windows-x64/boot.sdi,boot/windows-x64/boot.wim"
Emulating drive 0x81
FATAL: no bootmgr.exe
Press any key to reboot...
```

Any ideas?
Thanks for the great job!

**Comment by DimmKirr** [comment]
Hi, sorry to hear that you are having troubles. Can you tell me one thing, how much ram does your target machine have, just curious?

**Comment by ishtartec** [comment]
4GB, but I discovered where the problem was.
The current version of syslinux in ubuntu 14 is:

```
# dpkg -l | grep syslinux
ii  syslinux                            3:4.05+dfsg-6+deb8u1             amd64        collection of boot loaders
ii  syslinux-common                     3:4.05+dfsg-6+deb8u1             all          collection of boot loaders (common files)
```

That affects both pxelinux and linux.c32, and it looks like that version is too old. I've tried with syslinux 5 downloaded directly from kernel.org and it works now (I'm currently stuck in another point at winpe initial load related to unattended/script with an internal 500 server error, but I'll try to figure out how to continue ;-)).

**Comment by elJoeyJojo** [comment]
@ishtartec hey sorry to bother you with this, (very new to foreman) how did you upgrade the syslinux in your foreman server? i went to the kernel.org like you did and downloaded the 4.4.1 (quite big) and just not sure what to do from there but I am basically having the issue you had and I was hoping you could help me out. Thank You
Greetings from Canada

**Comment by ishtartec** [comment]
@elJoeyJojo use version 5 of syslinux (v4 looks too old, and 6 too new). Get the full syslinux v5 and just copy the linux.c32 file to the tftp structure:
https://www.kernel.org/pub/linux/utils/boot/syslinux/5.xx/

Greetings.

**Comment by elJoeyJojo** [comment]
@ishtartec Thanks for getting back to me dude, did it all and got past many errors but for some reason now I am seeing this error:

"No DEFAULT or UI configuration directive found!" 

I downloaded those files through wget kernel.org/pub/.... moved the files over to /tftpboot/ 
Changed permissiosn to foreman-proxy to be sure but it doesn't wanna do anything. 

Any idea?

**Comment by elJoeyJojo** [comment]
@ishtartec i finally got into the WinPE Configuraiton but now I get the 

Downloading Setup Script
http://puppet.domain.com/unattended/script: 
ERROR 404: Not Found

My templates seem to render correct, I can preview them without any issue and my Settings/Provisioning under "unatteded_url" is set to http://puppet.domain.com" 

Any idea?
