### ISSUE TITLE
pxelinux template issue with linux.c32

### ISSUE THREAD

**Issue by el-psycho** [kireevco/wimaging#29]
Hi,

I'm having the same problem as issue #28 

I'm running foreman 1.10 on CentOS 7.
Test pxe client is on a VirtualBox VM with 8GB of ram and a hard disk VMDK with 250GB.

I was getting the "Kernel load failure (insufficient memory?)" error when using linux.c32 from syslinux4.05 that can be installed from the CentOS7 repos so I tried what @ishtartec mentioned on issue #28 and downloaded syslinux5.10 from:
https://www.kernel.org/pub/linux/utils/boot/syslinux/5.xx/
and used the linux.c32 file there with foreman tftp, but now I get an error that says "linux.c32: not a COM32R image".

Does anyone know what I could be missing?
Thanks.

**Comment by el-psycho** [comment]
Hi, I've solved my problem. The syslinux version that worked for me was [syslinux-5.01.tar.xz](https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-5.01.tar.xz)

I extracted the file above and rsynced the following files to /var/lib/tftpboot/
chain.c32
ldlinux.c32
libcom32.c32
libutil.c32
linux.c32
pxelinux.0
vesamenu.c32

After that, it finally worked. I can boot to the Windows PE environment.
~~I now have a different problem with peSetup.cmd for which I'll open a different issue.~~

NOTE: It should be mentioned on the documentation that your foreman hosts (the hosts you want to image) must have an IP address associated with them in foreman or the peSetup.cmd script will fail to download.

Thanks.

**Comment by elJoeyJojo** [comment]
@el-psycho Hey dude, I keep getting another error, for some reason I don't even get those errors you got: :-1: 

I get this: 
![foreman5](https://cloud.githubusercontent.com/assets/17091968/12956556/77ee7256-cfdd-11e5-8742-ff620270f169.jpg)

![foreman4](https://cloud.githubusercontent.com/assets/17091968/12956573/80661650-cfdd-11e5-8926-1fcb1f9bef4e.jpg)

**Comment by elJoeyJojo** [comment]
@el-psycho btw, where did you find the ldlinux.c32 file? I also downloaded syslinux 5.10 and I can't find the damn file and it keeps asking for it :-1:

**Comment by elJoeyJojo** [comment]
@el-psycho never mind I found it, that fucker is pretty hidden but now I am just getting the "No DEFAULT or UI configuration directive found!" any idea?

**Comment by el-psycho** [comment]
@elJoeyJojo Looks like your WAIK PXELinux template is not rendering properly. Mine looks like this in the input tab:

``` erb
<%#
kind: PXELinux
name: WAIK default PXELinux
%>
DEFAULT wimbootpe
LABEL wimbootpe
     com32 linux.c32 boot/wimboot
     append initrdfile=<%= @host.operatingsystem.bootfile(@host.arch,:bcd) %>,<%= @host.operatingsystem.bootfile(@host.arch,:bootsdi) %>,<%= @host.operatingsystem.bootfile(@host.arch,:bootwim) %>
```

And in the Preview tab it looks like this:

```
DEFAULT wimbootpe
LABEL wimbootpe
     com32 linux.c32 boot/wimboot
     append initrdfile=boot/windows-x86_64/bcd,boot/windows-x86_64/boot.sdi,boot/windows-x86_64/boot.wim
```

**Comment by elJoeyJojo** [comment]
@el-psycho hey Kevin, thanks for getting back to me:

I think i'ts pretty similar to yours:

**Comment by elJoeyJojo** [comment]
`kind: PXELinux
 name: WAIK default PXELinux
 %>
-DEFAULT winPE

-LABEL winPE
-    KERNEL /Boot/startrom.0
  +DEFAULT menu
  +PROMPT 0
  +MENU TITLE PXE Menu
  +TIMEOUT 200
  +TOTALTIMEOUT 6000
  +ONTIMEOUT local
  +
  +LABEL menu
-     MENU LABEL Wimboot via pxelinux
-     COM32 linux.c32 boot/wimboot
-     APPEND initrdfile=boot/windows-x64/bcd,boot/windows-x64/boot.sdi,boot/windows-x64/boot.wim
  `

**Comment by el-psycho** [comment]
@elJoeyJojo This part is very important:

```
<%#
kind: PXELinux
name: WAIK default PXELinux
%>
```

That's a comment, and it has to start with  <%#  and end with  %>
https://docs.puppetlabs.com/puppet/latest/reference/lang_template_erb.html#comment-tags

**Comment by el-psycho** [comment]
Also, why are you using dashes with -DEFAULT and -LABEL? just make it like the wimaging docs say and when that's working make your changes.
Also, read this:
http://www.syslinux.org/wiki/index.php/Config

**Comment by elJoeyJojo** [comment]
@el-psycho I basically got all these templates from the wimaging github files, I only changed the path and left everything the same. I just added that <%# but didn't seem to do anything. I am not even sure if it's even trying to pull anything or if it's just a linux.c32 file error? I'll make my template like yours and see if that works. Thanks for all your help btw

**Comment by elJoeyJojo** [comment]
@el-psycho Nope, no luck. I changed it like yours and made sure the path is correct but I still get the error.

**Comment by elJoeyJojo** [comment]
@el-psycho hey Kevin, dumb question but when you downloaded the kernel syslinux-5.10 to your Foreman server did you just copy the files over to /var/lib/tftpboot/ ?
Someone mentioned something about compiling them but I thought it was just a copy to folder step. Any idea?

**Comment by el-psycho** [comment]
@elJoeyJojo The version that worked for me was syslinux **5.01**, and yes, I just transferred the files to /var/lib/tftpboot/, overwriting any existing versions of those files if they existed. I did not have to compile anything.

**Comment by elJoeyJojo** [comment]
@el-psycho I think the only difference is that I am using Ubuntu and you are using CentOS. I have a feeling a messed up something because I moved back the /usr/lib/syslinux/linux.c32 in there and still doesn't give me any different errors

**Comment by elJoeyJojo** [comment]
@el-psycho SUCCESS SUCCESS!!!! it started encapsulating :) :+1: 
The problem was that I made changes to the template but I had not made changes to the actual 01:00:00:00 MAC address file in /pxelinux.cfg/ 

Now I'm stuck on 

/unattended/script: 
ERROR 404: Not Found

**Comment by elJoeyJojo** [comment]
@el-psycho this is in WinPE though so I'm finally out of the PXE Boot errors :)

**Comment by elJoeyJojo** [comment]
![image](https://cloud.githubusercontent.com/assets/17091968/12965949/302f01ba-d00f-11e5-86a3-a39271930f00.png)

This is the error I get now

**Comment by elJoeyJojo** [comment]
Actually a better error are these 3 templates when I get on preview:

![image](https://cloud.githubusercontent.com/assets/17091968/12966060/d4b69a9a-d00f-11e5-87f7-1dab6ed242e2.png)

**Comment by elJoeyJojo** [comment]
@el-psycho  i finally got into the WinPE Configuraiton but now I get the

Downloading Setup Script
http://puppet.domain.com/unattended/script: 
ERROR 404: Not Found

My templates seem to render correct, I can preview them without any issue and my Settings/Provisioning under "unatteded_url" is set to http://puppet.domain.com"

Any idea?

**Comment by DimmKirr** [comment]
@all sorry for causing so much trouble folks :) I'm writing something really nice and easy that will download all required files automatically. I appreciate everyone here testing, this will definitely help in building a better wimaging 2.0 :) 

Here's a set of commands to get a right syslinux. run it on your foreman server with tftpd:

```
cd /var/lib/tftpboot/

# Make a backup of our current pxelinux just in case...
tar -zcf ~/foreman-pxe-backup.tgz .

# Download syslinux 5.01 and extract nessesary files
wget https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-5.01.tar.xz
tar -xf syslinux-5.01.tar.xz
cp syslinux-5.01/com32/chain/chain.c32 .
cp syslinux-5.01//com32/elflink/ldlinux/ldlinux.c32 .
cp syslinux-5.01/com32/lib/libcom32.c32 .
cp syslinux-5.01/com32/libutil/libutil.c32 .
cp syslinux-5.01/com32/modules/linux.c32 .
cp syslinux-5.01/core/pxelinux.0 .
cp syslinux-5.01/com32/menu/vesamenu.c32 .

rm -rf syslinux-5.01*

# Get wimboot
wget http://git.ipxe.org/releases/wimboot/wimboot-latest.zip
unzip wimboot-latest.zip
cp wimboot-*/wimboot boot/
rm -rf wimboot-*
```

**Comment by elJoeyJojo** [comment]
@kireevco Thanks! Yeah those instructions would've been quite nice as it took me quite a bit to figure out that syslinux issue but it will make everything easier for the next bunch

**Comment by brandonweeks** [comment]
```
syslinux-6.03/bios/com32/elflink/ldlinux/ldlinux.c32
syslinux-6.03/bios/com32/lib/libcom32.c32
syslinux-6.03/bios/com32/libutil/libutil.c32
syslinux-6.03/bios/com32/menu/menu.c32
syslinux-6.03/bios/com32/modules/linux.c32
syslinux-6.03/bios/core/pxelinux.0
```

These are the files required to use syslinux 6.03.
