### ISSUE TITLE
2012 Server

### ISSUE THREAD

**Issue by matthieudolci** [kireevco/wimaging#3]
Hello @kireevco ,

Do you plan to have the tool ready for 2012 server in a near futur?

Thanks,

Matthieu

**Comment by DimmKirr** [comment]
Yes, planning to do it soon, should not be hard - couple more lines of
code.
Core toolchain will remain unchanged.

## 

Dmitry

**Comment by matthieudolci** [comment]
Awesome!!! 

Looking forward to it

**Comment by DimmKirr** [comment]
@matthieudolci please check it out, 2012r2 should work now.
