### ISSUE TITLE
token not getting generated for foreman_url(built)

### ISSUE THREAD

**Issue by vsarin** [kireevco/wimaging#32]
Hi, 

Is there any issue with current build I am not able to see token getting generated for built option.

Token generated for finish, provision and user_data
![image](https://cloud.githubusercontent.com/assets/20552724/16978113/d561ac8c-4e77-11e6-8011-fb4242f70f08.png)

No token generated for built.

![image](https://cloud.githubusercontent.com/assets/20552724/16978137/f5cbcc00-4e77-11e6-9b5e-ea033a65cbac.png)

Below is the trace of prxoy.log

D, [2016-07-20T12:47:18.395768 #2618] DEBUG -- : Retrieving a template from http://sdin-swt-ct-04.sdcorp.global.com:8000//unattended/built?token=527dc2a4-ad34-4821-bdb1-b73f3f348498&url=http%3A%2F%2Fsdin-swt-ct-04.sdcorp.global.com%3A8000
D, [2016-07-20T12:47:18.395998 #2618] DEBUG -- : HTTP headers: {"X-Forwarded-For"=>"10.65.225.158, sdin-swt-ct-04.sdcorp.global.com", "ACCEPT_LANGUAGE"=>"en-US,en;q=0.8", "UPGRADE_INSECURE_REQUESTS"=>"1", "CONNECTION"=>"keep-alive", "ACCEPT_ENCODING"=>"gzip, deflate, sdch", "CACHE_CONTROL"=>"max-age=0", "USER_AGENT"=>"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36", "ACCEPT"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8"}
E, [2016-07-20T12:47:18.482038 #2618] ERROR -- : Failed to retrieve built template for {"token"=>"527dc2a4-ad34-4821-bdb1-b73f3f348498", "kind"=>"built"}: Error retrieving built for {"token"=>"527dc2a4-ad34-4821-bdb1-b73f3f348498", :url=>"http://sdin-swt-ct-04.sdcorp.global.com:8000"} from sdin-swt-ct-04.sdcorp.global.com: Net::HTTPInternalServerError
D, [2016-07-20T12:47:18.482130 #2618] DEBUG -- : Error retrieving built for {"token"=>"527dc2a4-ad34-4821-bdb1-b73f3f348498", :url=>"http://sdin-swt-ct-04.sdcorp.global.com:8000"} from sdin-swt-ct-04.sdcorp.global.com: Net::HTTPInternalServerError (RuntimeError)
/usr/share/foreman-proxy/modules/templates/template_proxy_request.rb:24:in `get_template'
/usr/share/foreman-proxy/modules/templates/templates_api.rb:19:in`GET /:kind'
/usr/share/foreman-proxy/lib/proxy/helpers.rb:14:in `log_halt'
/usr/share/foreman-proxy/modules/templates/templates_api.rb:18:in`GET /:kind'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in`route'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:521:in`route_eval'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:497:in`catch'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:476:in`each'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:601:in`dispatch!'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in`instance_eval'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in`catch'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:411:in`call!'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/commonlogger.rb:18:in`call'
/usr/share/foreman-proxy/lib/proxy/log.rb:60:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/showexceptions.rb:24:in`call'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/urlmap.rb:47:in`call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in `each'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in`call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/builder.rb:77:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/content_length.rb:13:in`call'
/usr/lib/ruby/gems/1.8/gems/rack-1.1.0/lib/rack/handler/webrick.rb:48:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:92:in`each'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:23:in`start'
/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
/usr/share/foreman-proxy/lib/launcher.rb:137:in`launch'
/usr/share/foreman-proxy/lib/launcher.rb:137:in `initialize'
/usr/share/foreman-proxy/lib/launcher.rb:137:in`new'
/usr/share/foreman-proxy/lib/launcher.rb:137:in `launch'
/usr/share/foreman-proxy/bin/smart-proxy:6
I, [2016-07-20T12:47:18.482402 #2618]  INFO -- : 10.65.225.158 - - [20/Jul/2016 12:47:18] "GET /built?token=527dc2a4-ad34-4821-bdb1-b73f3f348498 HTTP/1.1" 500 320 0.0879

Finish Provision Template 

@echo off
  echo Activating administrator
  net user administrator /active:yes
echo "10.65.168.18 sdin-swt-ct-04.sdcorp.global.com" > C:\Windows\System32\drivers\etc\hosts

  set ctr=0
  set nettimeout=10
  set nwhost=sdin-swt-ct-04.sdcorp.global.com

  (echo Updating time)
  (sc config w32time start= auto)
  sc start w32time
  :ntp_testip
    ::ipconfig /renew
    ping -n 1 %nwhost% > NUL
    if %errorlevel% == 0 goto ntp_testip_ok
    timeout /t 10 >NUL
    set /a ctr=ctr+1
    echo Retry network. Run %ctr% time(s)
    if %ctr% GTR %nettimeout% (
        echo Network error! Exiting.
        exit 1
        )
    goto ntp_testip
  :ntp_testip_ok

  echo Ping to %nwhost% OK!

  echo sync time
  w32tm /resync
  w32tm /resync

  :: You can join your machine to the domain right here >

  :: < You can join your machine to the domain right here

  echo safely remove files
  sdelete.exe -accepteula -p 2 -r c:\wimaging
  sdelete.exe -accepteula -p 2 c:\Windows\Panther\unattend.xml
  sdelete.exe -accepteula -p 2 C:\Windows\Setup\Scripts\SetupComplete.cmd
  sdelete.exe -accepteula -p 2 -r c:\minint
  sdelete.exe -accepteula -p 2 -r c:\wimaging

```
echo Running extra commands
```

  @echo off
echo Installing puppet
start /w "" msiexec /qn /i C:\extras\puppet.msi PUPPET_AGENT_STARTUP_MODE=Manual PUPPET_MASTER_SERVER="sdin-swt-ct-04.sdcorp.global.com"
echo set puppet to auto start
sc config puppet start= auto
sc query puppet
  echo cleaning up extras
  sdelete.exe -accepteula -p 2 -r c:\extras

  echo Tell foreman build mode has finished
  wget.exe http://sdin-swt-ct-04.sdcorp.global.com:8000/unattended/built?token=527dc2a4-ad34-4821-bdb1-b73f3f348498

  sdelete.exe -accepteula -p 2 -r c:\deploy

  echo remove leftover directories
  rmdir /s /q c:\wimaging
  rmdir /s /q c:\minint
  rmdir /s /q c:\deploy
  rmdir /s /q c:\extras

  echo rebooting...
  shutdown /r /t 5

Let me know if you need more information.

Thanks
-Vishal Sarin

**Comment by vsarin** [comment]
Hi, The foreman URL is not getting replaced with IP address in the CentOS 6.8 Version but same is getting  replaced in CentOS6.8 Version. I thoughts its an issue with the WAIK script but it was puppet issue, Please close the issue.

**Comment by vsarin** [comment]
Not an issue

**Comment by DimmKirr** [comment]
@vsarin can you provide some details, what was the puppet issue?

**Comment by vsarin** [comment]
Hi Kireevco, In CentOS 6.8 puppet (version 3.7.2) is not able to generate token for (foreman_url)built but same is getting generated in CentOS 7.2 puppet version 4.5.7. Since it was not getting generated in 6.8 So when even installation is over the foreman is still not informed about the installation complete. It remains in installation pending state.
So when a windows Image boots the state of the host is installation pending and host is never managed.
Let me know if you need more information.

**Comment by DimmKirr** [comment]
`foreman_url` is generated by foreman only. Honestly, I don't even have puppet in my setup, so this is something else.
