### ISSUE TITLE
Questions re some config options

### ISSUE THREAD

**Issue by NuxRo** [kireevco/wimaging#4]
Hi,

https://github.com/kireevco/wimaging/blob/master/tools/install.root/wimaging/_config.cmd.sample

domain, user and password - what are these for here? If I'm building a generic dedicated server for a customer (without puppet), what should be in here?

Thanks

**Comment by DimmKirr** [comment]
@NuxRo Hi,

It's your credentials to a windows share. 
PLS let me know if you have other questions.

**Comment by NuxRo** [comment]
Thanks, I do have more questions. :)

I assume it's this "_config.cmd.sample" that needs to be copied to ".\tools\install.root\Windows\Setup\Scripts\config.cmd", right? 

The README is slightly misleading saying:
"Rename .\tools\install.root\Windows\Setup\Scripts\config.cmd.sample to config.cmd"

**Comment by DimmKirr** [comment]
Just rename it and keep in the same folder :)
Feel free to reach me out on gitter.
