### ISSUE TITLE
ipxe / bootdisk

### ISSUE THREAD

**Issue by edestecd** [kireevco/wimaging#41]
We have several static only vlans that we use Foreman bootdisk and ipxe for on Linux.
Have you guys ever done anything like this for Windows?  Is there a way to make ipxe work with wimaging or wimboot? Do you know of an alternative for Foreman?

**Comment by helge000** [comment]
No, never used iPXE - booting. However wimboot is from the iPXE project. Therefore, I assume it works with iPXE. 
There are some cases where wimboot crashes. In these I use a USB sick to boot the instance (wich runs the `boot.wim` created). 

I'd say it is a fair assumption you can get the whole installation process running if you can get `boot.wim` to load in the first place.

**Comment by helge000** [comment]
Any news? Please reopen when you need more assistance
