### ISSUE TITLE
Params.ps1 using constant instead of variable for DISM location

### ISSUE THREAD

**Issue by TechnoTaff** [kireevco/wimaging#42]
This caused a couple of hours of grief but thankfully I've sorted it.

Functions.ps1, Line 221 reads:

Invoke-Expression "& 'dism' /mount-wim /wimfile:$wim_file /mountdir:$mount_dir /name:'$wim_image_name'" 

It should read:

Invoke-Expression "& '$dism' /mount-wim /wimfile:$wim_file /mountdir:$mount_dir /name:'$wim_image_name'"

**Comment by MattzFiber** [comment]
I've had this issue too, the above fixed it for me. Thank you for pointing it out!

**Comment by helge000** [comment]
Fixed by #40
