### ISSUE TITLE
Trouble with PXE boot 

### ISSUE THREAD

**Issue by rangya2210** [kireevco/wimaging#45]
Environment: Foreman, VMWare and trying to build windows 2016 VMs using foreman.
Getting stuck in the wimboot process. The VM pxe boots, then downloads wimboot but then fails on boot.sdi and boot.wim. 
Is there a good documentation or suggestion to make the pxeboot work with wimboot to provision windows VMs?

Regards,
Rangaa

**Comment by DimmKirr** [comment]
@rangaa Can you please provide more info about the errors you're experiencing. I'm sure that would shed some light on what is going on.

Thanks

**Comment by rangya2210** [comment]
Here are the screen shots of the pxe config file (which has several iterations of the edits we have tries) and screen shot of the console message.

> DEFAULT menu
> LABEL menu
>   kernel wimboot
>   initrd /var/lib/tftpboot/boot.sdi
>   initrd /var/lib/tftpboot/boot.wim
>   initrd /var/lib/tftpboot/bcd
>   initrd /var/lib/tftpboot/bootmgr.exe
>       # KERNEL win/wimboot 
>       # COM32 linux.c32 /var/lib/tftpboot/wim/wimboot
> 
>      # APPEND  initrd=bootmgr.exe
>      # COM32 linux.c32 /var/lib/tftpboot/wim/wimboot
>      # KERNEL /var/lib/tftpboot/win/wimboot
>      # APPEND  /var/lib/tftpboot/win/wimboot initrdfile=/var/lib/tftpboot/bcd,/var/lib/tftpboot/boot.sdi,/var/lib/tftpboot/boot.wim
>      # APPEND  wimboot initrdfile=/var/lib/tftpboot/bcd,/var/lib/tftpboot/boot.sdi,/var/lib/tftpboot/boot.wim 
> 
>      #/var/lib/tftpboot/boot/Windows/wimboot
>      #initrdfile=boot/windows-x64/bcd,boot/windows-x64/boot.sdi,boot/windows-x64/boot.wim
> #
> #DEFAULT winPE
> 
> #LABEL winPE
>     #KERNEL /boot/Windows/wimboot
> 
> 

![screen shot](https://user-images.githubusercontent.com/11186096/29685191-b4a8077e-88e2-11e7-9c41-7ca272ab964c.png)

**Comment by rangaa** [comment]
`DEFAULT menu
LABEL menu
  kernel wimboot
  initrd /var/lib/tftpboot/boot.sdi
  initrd /var/lib/tftpboot/boot.wim
  initrd /var/lib/tftpboot/bcd
  initrd /var/lib/tftpboot/bootmgr.exe
      # KERNEL win/wimboot 
      # COM32 linux.c32 /var/lib/tftpboot/wim/wimboot

     # APPEND  initrd=bootmgr.exe
     # COM32 linux.c32 /var/lib/tftpboot/wim/wimboot
     # KERNEL /var/lib/tftpboot/win/wimboot
     # APPEND  /var/lib/tftpboot/win/wimboot initrdfile=/var/lib/tftpboot/bcd,/var/lib/tftpboot/boot.sdi,/var/lib/tftpboot/boot.wim
     # APPEND  wimboot initrdfile=/var/lib/tftpboot/bcd,/var/lib/tftpboot/boot.sdi,/var/lib/tftpboot/boot.wim 

     #/var/lib/tftpboot/boot/Windows/wimboot
     #initrdfile=boot/windows-x64/bcd,boot/windows-x64/boot.sdi,boot/windows-x64/boot.wim
#
#DEFAULT winPE

#LABEL winPE
    #KERNEL /boot/Windows/wimboot`

**Comment by helge000** [comment]
Hello,

syslinux 4 does not work. It crashes in the middle of loading, as you could verify. 

You need to swap it with syslinux 5+. I think I did mention this requirement somewhere in the docs. You could further try the iPXE road, though I cannot assist you with this any further.

**Comment by helge000** [comment]
@rangaa , I actually did not mention Syslinux 5. Sorry for that, 6cdbaf0 added the line in README.md

**Comment by rangya2210** [comment]
@helge000 et. al.
Thanks Daniel, I was using syslinux 5. It ended up being needing the correct version of ldlinux.c32 and additional libcom32.c32 files for it to work. At this moment, my VM is booting windows through PXE and I am going to start working on the provisioning templates.
Thanks for help and willingness to assist. This issue is resolved.

Rangaa

**Comment by helge000** [comment]
@rangaa, happy you got PXELinux working.

Turns out our documentation is missing this step. Since I run only one Foreman instance and did the same about two years back - I can't really remember which files where needed. It would be great if you could add the nessesary steps in a PR in the [doc foreman, number (I)](https://github.com/kireevco/wimaging/blob/master/doc/foreman.md#i-download-wimboot).

**Comment by LiranNis** [comment]
The instructions for these steps are written in [foreman-wimaging wiki](https://github.com/kireevco/foreman-wimaging/wiki/TFTP-PXE-Server)
I think it will be better to add this wiki to the docs.
