### ISSUE TITLE
StartRom and boot.sdi not found

### ISSUE THREAD

**Issue by nratineau** [kireevco/wimaging#5]
During the TFTP PXE config generation foreman is trying to download 2 files:
startrom.0 and boot.sdi however they dont seem to be copied by any script?
http://deployhost/install/server-2012r2x64.standard/images/startrom.0
then renamed boot/windows-6.3-x64-startrom.0
http://deployhost/install/server-2012r2x64.standard/images/boot.sdi
then renamed boot/windows-6.3-x64-boot.sdi

Did I miss something?
Thanks

**Comment by mikenowak** [comment]
Not sure how you've got this setup, but I serve these files to clients over tftp, you seem to attempt to leverage http instead.

Speaking of startrom.0 I dont think this is required, I think you need to modify your WAIK PXE template in foreman; see theforeman/community-templates@4a393641ad281f637b7183becbc7019de6a0f5d0 as an example.

 I believe that Init-PxeTools.ps1 does copy the boot.sdi and other files of interest to install_dir, but you'd then need to manually transfer these to your tftp directory.

**Comment by DimmKirr** [comment]
These files are shipped over tftp. Http is used when boot.wim is already up.
Newest foreman and foreman-proxy will take care of downloading all boot loader files to your tftp directory (wimboot, boot.sdi, and others)

One thing that you need to check is that your pxelinux works with wimaging.

Please let me know if you need more info

**Comment by DimmKirr** [comment]
...and I apologize in advance for gaps in documentation.... :)

**Comment by nratineau** [comment]
Yes after applying the patch provided by kireevco I was able to get the boot going. Howver I had to make sure to use syslinux 6.03 with Xenserver otherwise the system would fail to load wimboot 2.4.1 which wimaging download.

**Comment by DimmKirr** [comment]
@nratineau awesome. Did you get network & disk drivers working without issues?

**Comment by nratineau** [comment]
Yes without any prob using this How-To as the source:
http://blogs.citrix.com/2015/03/03/how-to-create-a-winpe-boot-disc-with-xenserver-paravirtualized-network-driver-installed/
I'll close the issue as it's good on my side :)
