### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by mikenowak** [kireevco/wimaging#7]
Hi Dmirty,

I need to add support for windows7, which I nearly got working on my end, but before I start submitting changes, a question to you is - do you have any preference as to what the $os variable should be?

You use $os = "server-2008r2" as an example.

**Comment by DimmKirr** [comment]
Hi, 
`win7x64` or something like that? or `windows7x64` I'd prefer to include bitness.

Thank you for your contribution :)

**Comment by mikenowak** [comment]
Should be working, but I still need to figure out how to add powershell support to boot.wim, which I can see you've commented out for some reason.

```
    Write-Host "WinPE-PowerShell3.cab"
    $package_path += "/PackagePath:'${update_dir}\WinPE-PowerShell3.cab'"        
```

Any particular reason why this is disabled?

**Comment by DimmKirr** [comment]
I just try to stay bare bones. Any particular reason why you need powershell?

**Comment by mikenowak** [comment]
I have thought that wget.vsb requires it in order to download the provisioning scripts from foreman

**Comment by DimmKirr** [comment]
Doesn't require. It uses cscript only. So I would prefer not to include powershell of possible for now please

**Comment by mikenowak** [comment]
That's absolutely fine.

I think that I've been mistakenly using winpe.wim which doesn't contain cscript or anything.

I am pretty sure, that I was getting an error message "No such interface supported". Manually integrating packages you've commented out had fixed this.

I am going to try this with boot.wim from the Windows media and report if this is still an issue.

Otherwise, I think we're looking OK.

**Comment by mikenowak** [comment]
will submit a PR once I refactor the code
