### ISSUE TITLE
Statically defined deployment share

### ISSUE THREAD

**Issue by mikenowak** [kireevco/wimaging#9]
Do we really need to define `%deploymentShare%` in the init scripts?

You do this:

`ping -n 1 %deploymentShare% > NUL`

and then 

`echo Downloading Setup Script
%deployRoot%\wget.vbs http://%foremanHost%/unattended/script %deployRoot%\peSetup.cmd`

I'd rather check the network availability by pinging the `%foremanHost%`

and move all the logic responsible for mounting/interacting with the `%deploymentShare%` to foreman script.

This would help in situations where there are multiple locations or networks in our deployment that require `%deploymentShare%` to differ slightly.

Let me know what you think and I will work on this.

**Comment by DimmKirr** [comment]
@mikenowak make sense. I like what you are proposing.

**Comment by DimmKirr** [comment]
@helge000 made some signigicant changes, @mikenowak would you mind create a new pr?
